[package]
name = "terminal_fluid_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = "0.27"
rayon = "1.10.0"
log4rs = "1.3.0"
log = "0.4"
